
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)

interface _GlobalComponents {
      'Badge': typeof import("../../app/components/ui/badge/index")['Badge']
    'Button': typeof import("../../app/components/ui/button/index")['Button']
    'FooterAppFooter': typeof import("../../app/components/footer/appFooter.vue")['default']
    'IndexAboutSection': typeof import("../../app/components/index/aboutSection.vue")['default']
    'IndexCaseStudySection': typeof import("../../app/components/index/caseStudySection.vue")['default']
    'IndexContactSection': typeof import("../../app/components/index/contactSection.vue")['default']
    'IndexHeroSection': typeof import("../../app/components/index/heroSection.vue")['default']
    'IndexProjectsSection': typeof import("../../app/components/index/projectsSection.vue")['default']
    'NuxtWelcome': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
    'ClientOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtTime': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Align': typeof import("@tresjs/cientos")['Align']
    'AnimatedSprite': typeof import("@tresjs/cientos")['AnimatedSprite']
    'Backdrop': typeof import("@tresjs/cientos")['Backdrop']
    'BakeShadows': typeof import("@tresjs/cientos")['BakeShadows']
    'BaseCameraControls': typeof import("@tresjs/cientos")['BaseCameraControls']
    'Billboard': typeof import("@tresjs/cientos")['Billboard']
    'Box': typeof import("@tresjs/cientos")['Box']
    'CameraControls': typeof import("@tresjs/cientos")['CameraControls']
    'CatmullRomCurve3': typeof import("@tresjs/cientos")['CatmullRomCurve3']
    'Circle': typeof import("@tresjs/cientos")['Circle']
    'Cone': typeof import("@tresjs/cientos")['Cone']
    'ContactShadows': typeof import("@tresjs/cientos")['ContactShadows']
    'CubeCamera': typeof import("@tresjs/cientos")['CubeCamera']
    'CustomShaderMaterial': typeof import("@tresjs/cientos")['CustomShaderMaterial']
    'Cylinder': typeof import("@tresjs/cientos")['Cylinder']
    'Dodecahedron': typeof import("@tresjs/cientos")['Dodecahedron']
    'Edges': typeof import("@tresjs/cientos")['Edges']
    'Environment': typeof import("@tresjs/cientos")['Environment']
    'FBXModel': typeof import("@tresjs/cientos")['FBXModel']
    'Fbo': typeof import("@tresjs/cientos")['Fbo']
    'Fit': typeof import("@tresjs/cientos")['Fit']
    'GLTFModel': typeof import("@tresjs/cientos")['GLTFModel']
    'GlobalAudio': typeof import("@tresjs/cientos")['GlobalAudio']
    'GradientTexture': typeof import("@tresjs/cientos")['GradientTexture']
    'Grid': typeof import("@tresjs/cientos")['Grid']
    'HolographicMaterial': typeof import("@tresjs/cientos")['HolographicMaterial']
    'Html': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Html']
    'Icosahedron': typeof import("@tresjs/cientos")['Icosahedron']
    'Image': typeof import("@tresjs/cientos")['Image']
    'KeyboardControls': typeof import("@tresjs/cientos")['KeyboardControls']
    'Lensflare': typeof import("@tresjs/cientos")['Lensflare']
    'Levioso': typeof import("@tresjs/cientos")['Levioso']
    'Lightformer': typeof import("@tresjs/cientos")['Lightformer']
    'Line2': typeof import("@tresjs/cientos")['Line2']
    'MapControls': typeof import("@tresjs/cientos")['MapControls']
    'Mask': typeof import("@tresjs/cientos")['Mask']
    'MeshDiscardMaterial': typeof import("@tresjs/cientos")['MeshDiscardMaterial']
    'MeshGlassMaterial': typeof import("@tresjs/cientos")['MeshGlassMaterial']
    'MeshReflectionMaterial': typeof import("@tresjs/cientos")['MeshReflectionMaterial']
    'MeshWobbleMaterial': typeof import("@tresjs/cientos")['MeshWobbleMaterial']
    'MouseParallax': typeof import("@tresjs/cientos")['MouseParallax']
    'Ocean': typeof import("@tresjs/cientos")['Ocean']
    'Octahedron': typeof import("@tresjs/cientos")['Octahedron']
    'OrbitControls': typeof import("@tresjs/cientos")['OrbitControls']
    'Outline': typeof import("@tresjs/cientos")['Outline']
    'Plane': typeof import("@tresjs/cientos")['Plane']
    'PointerLockControls': typeof import("@tresjs/cientos")['PointerLockControls']
    'PositionalAudio': typeof import("@tresjs/cientos")['PositionalAudio']
    'Precipitation': typeof import("@tresjs/cientos")['Precipitation']
    'Reflector': typeof import("@tresjs/cientos")['Reflector']
    'Ring': typeof import("@tresjs/cientos")['Ring']
    'RoundedBox': typeof import("@tresjs/cientos")['RoundedBox']
    'SVG': typeof import("@tresjs/cientos")['SVG']
    'Sampler': typeof import("@tresjs/cientos")['Sampler']
    'ScreenSizer': typeof import("@tresjs/cientos")['ScreenSizer']
    'ScreenSpace': typeof import("@tresjs/cientos")['ScreenSpace']
    'ScrollControls': typeof import("@tresjs/cientos")['ScrollControls']
    'Sky': typeof import("@tresjs/cientos")['Sky']
    'Smoke': typeof import("@tresjs/cientos")['Smoke']
    'SoftShadows': typeof import("@tresjs/cientos")['SoftShadows']
    'Sparkles': typeof import("@tresjs/cientos")['Sparkles']
    'Sphere': typeof import("@tresjs/cientos")['Sphere']
    'Stars': typeof import("@tresjs/cientos")['Stars']
    'Stats': typeof import("@tresjs/cientos")['Stats']
    'StatsGl': typeof import("@tresjs/cientos")['StatsGl']
    'Superformula': typeof import("@tresjs/cientos")['Superformula']
    'Tetrahedron': typeof import("@tresjs/cientos")['Tetrahedron']
    'Text3D': typeof import("@tresjs/cientos")['Text3D']
    'Torus': typeof import("@tresjs/cientos")['Torus']
    'TorusKnot': typeof import("@tresjs/cientos")['TorusKnot']
    'TransformControls': typeof import("@tresjs/cientos")['TransformControls']
    'Tube': typeof import("@tresjs/cientos")['Tube']
    'TresCanvas': typeof import("../../node_modules/.pnpm/@tresjs+nuxt@4.0.0_magicast@0.3.5_rollup@4.52.0_three@0.180.0_vite@7.1.6_jiti@2.5.1_lig_fb7d552ca8598111e4dec8a11730d93b/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']
    'TresCanvas': typeof import("../../node_modules/.pnpm/@tresjs+nuxt@4.0.0_magicast@0.3.5_rollup@4.52.0_three@0.180.0_vite@7.1.6_jiti@2.5.1_lig_fb7d552ca8598111e4dec8a11730d93b/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']
    'NuxtPage': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Head']
    'Body': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyBadge': LazyComponent<typeof import("../../app/components/ui/badge/index")['Badge']>
    'LazyButton': LazyComponent<typeof import("../../app/components/ui/button/index")['Button']>
    'LazyFooterAppFooter': LazyComponent<typeof import("../../app/components/footer/appFooter.vue")['default']>
    'LazyIndexAboutSection': LazyComponent<typeof import("../../app/components/index/aboutSection.vue")['default']>
    'LazyIndexCaseStudySection': LazyComponent<typeof import("../../app/components/index/caseStudySection.vue")['default']>
    'LazyIndexContactSection': LazyComponent<typeof import("../../app/components/index/contactSection.vue")['default']>
    'LazyIndexHeroSection': LazyComponent<typeof import("../../app/components/index/heroSection.vue")['default']>
    'LazyIndexProjectsSection': LazyComponent<typeof import("../../app/components/index/projectsSection.vue")['default']>
    'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/welcome.vue")['default']>
    'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
    'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
    'LazyClientOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/client-only")['default']>
    'LazyDevOnly': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/dev-only")['default']>
    'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-link")['default']>
    'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
    'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
    'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
    'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
    'LazyAlign': LazyComponent<typeof import("@tresjs/cientos")['Align']>
    'LazyAnimatedSprite': LazyComponent<typeof import("@tresjs/cientos")['AnimatedSprite']>
    'LazyBackdrop': LazyComponent<typeof import("@tresjs/cientos")['Backdrop']>
    'LazyBakeShadows': LazyComponent<typeof import("@tresjs/cientos")['BakeShadows']>
    'LazyBaseCameraControls': LazyComponent<typeof import("@tresjs/cientos")['BaseCameraControls']>
    'LazyBillboard': LazyComponent<typeof import("@tresjs/cientos")['Billboard']>
    'LazyBox': LazyComponent<typeof import("@tresjs/cientos")['Box']>
    'LazyCameraControls': LazyComponent<typeof import("@tresjs/cientos")['CameraControls']>
    'LazyCatmullRomCurve3': LazyComponent<typeof import("@tresjs/cientos")['CatmullRomCurve3']>
    'LazyCircle': LazyComponent<typeof import("@tresjs/cientos")['Circle']>
    'LazyCone': LazyComponent<typeof import("@tresjs/cientos")['Cone']>
    'LazyContactShadows': LazyComponent<typeof import("@tresjs/cientos")['ContactShadows']>
    'LazyCubeCamera': LazyComponent<typeof import("@tresjs/cientos")['CubeCamera']>
    'LazyCustomShaderMaterial': LazyComponent<typeof import("@tresjs/cientos")['CustomShaderMaterial']>
    'LazyCylinder': LazyComponent<typeof import("@tresjs/cientos")['Cylinder']>
    'LazyDodecahedron': LazyComponent<typeof import("@tresjs/cientos")['Dodecahedron']>
    'LazyEdges': LazyComponent<typeof import("@tresjs/cientos")['Edges']>
    'LazyEnvironment': LazyComponent<typeof import("@tresjs/cientos")['Environment']>
    'LazyFBXModel': LazyComponent<typeof import("@tresjs/cientos")['FBXModel']>
    'LazyFbo': LazyComponent<typeof import("@tresjs/cientos")['Fbo']>
    'LazyFit': LazyComponent<typeof import("@tresjs/cientos")['Fit']>
    'LazyGLTFModel': LazyComponent<typeof import("@tresjs/cientos")['GLTFModel']>
    'LazyGlobalAudio': LazyComponent<typeof import("@tresjs/cientos")['GlobalAudio']>
    'LazyGradientTexture': LazyComponent<typeof import("@tresjs/cientos")['GradientTexture']>
    'LazyGrid': LazyComponent<typeof import("@tresjs/cientos")['Grid']>
    'LazyHolographicMaterial': LazyComponent<typeof import("@tresjs/cientos")['HolographicMaterial']>
    'LazyHtml': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Html']>
    'LazyIcosahedron': LazyComponent<typeof import("@tresjs/cientos")['Icosahedron']>
    'LazyImage': LazyComponent<typeof import("@tresjs/cientos")['Image']>
    'LazyKeyboardControls': LazyComponent<typeof import("@tresjs/cientos")['KeyboardControls']>
    'LazyLensflare': LazyComponent<typeof import("@tresjs/cientos")['Lensflare']>
    'LazyLevioso': LazyComponent<typeof import("@tresjs/cientos")['Levioso']>
    'LazyLightformer': LazyComponent<typeof import("@tresjs/cientos")['Lightformer']>
    'LazyLine2': LazyComponent<typeof import("@tresjs/cientos")['Line2']>
    'LazyMapControls': LazyComponent<typeof import("@tresjs/cientos")['MapControls']>
    'LazyMask': LazyComponent<typeof import("@tresjs/cientos")['Mask']>
    'LazyMeshDiscardMaterial': LazyComponent<typeof import("@tresjs/cientos")['MeshDiscardMaterial']>
    'LazyMeshGlassMaterial': LazyComponent<typeof import("@tresjs/cientos")['MeshGlassMaterial']>
    'LazyMeshReflectionMaterial': LazyComponent<typeof import("@tresjs/cientos")['MeshReflectionMaterial']>
    'LazyMeshWobbleMaterial': LazyComponent<typeof import("@tresjs/cientos")['MeshWobbleMaterial']>
    'LazyMouseParallax': LazyComponent<typeof import("@tresjs/cientos")['MouseParallax']>
    'LazyOcean': LazyComponent<typeof import("@tresjs/cientos")['Ocean']>
    'LazyOctahedron': LazyComponent<typeof import("@tresjs/cientos")['Octahedron']>
    'LazyOrbitControls': LazyComponent<typeof import("@tresjs/cientos")['OrbitControls']>
    'LazyOutline': LazyComponent<typeof import("@tresjs/cientos")['Outline']>
    'LazyPlane': LazyComponent<typeof import("@tresjs/cientos")['Plane']>
    'LazyPointerLockControls': LazyComponent<typeof import("@tresjs/cientos")['PointerLockControls']>
    'LazyPositionalAudio': LazyComponent<typeof import("@tresjs/cientos")['PositionalAudio']>
    'LazyPrecipitation': LazyComponent<typeof import("@tresjs/cientos")['Precipitation']>
    'LazyReflector': LazyComponent<typeof import("@tresjs/cientos")['Reflector']>
    'LazyRing': LazyComponent<typeof import("@tresjs/cientos")['Ring']>
    'LazyRoundedBox': LazyComponent<typeof import("@tresjs/cientos")['RoundedBox']>
    'LazySVG': LazyComponent<typeof import("@tresjs/cientos")['SVG']>
    'LazySampler': LazyComponent<typeof import("@tresjs/cientos")['Sampler']>
    'LazyScreenSizer': LazyComponent<typeof import("@tresjs/cientos")['ScreenSizer']>
    'LazyScreenSpace': LazyComponent<typeof import("@tresjs/cientos")['ScreenSpace']>
    'LazyScrollControls': LazyComponent<typeof import("@tresjs/cientos")['ScrollControls']>
    'LazySky': LazyComponent<typeof import("@tresjs/cientos")['Sky']>
    'LazySmoke': LazyComponent<typeof import("@tresjs/cientos")['Smoke']>
    'LazySoftShadows': LazyComponent<typeof import("@tresjs/cientos")['SoftShadows']>
    'LazySparkles': LazyComponent<typeof import("@tresjs/cientos")['Sparkles']>
    'LazySphere': LazyComponent<typeof import("@tresjs/cientos")['Sphere']>
    'LazyStars': LazyComponent<typeof import("@tresjs/cientos")['Stars']>
    'LazyStats': LazyComponent<typeof import("@tresjs/cientos")['Stats']>
    'LazyStatsGl': LazyComponent<typeof import("@tresjs/cientos")['StatsGl']>
    'LazySuperformula': LazyComponent<typeof import("@tresjs/cientos")['Superformula']>
    'LazyTetrahedron': LazyComponent<typeof import("@tresjs/cientos")['Tetrahedron']>
    'LazyText3D': LazyComponent<typeof import("@tresjs/cientos")['Text3D']>
    'LazyTorus': LazyComponent<typeof import("@tresjs/cientos")['Torus']>
    'LazyTorusKnot': LazyComponent<typeof import("@tresjs/cientos")['TorusKnot']>
    'LazyTransformControls': LazyComponent<typeof import("@tresjs/cientos")['TransformControls']>
    'LazyTube': LazyComponent<typeof import("@tresjs/cientos")['Tube']>
    'LazyTresCanvas': LazyComponent<typeof import("../../node_modules/.pnpm/@tresjs+nuxt@4.0.0_magicast@0.3.5_rollup@4.52.0_three@0.180.0_vite@7.1.6_jiti@2.5.1_lig_fb7d552ca8598111e4dec8a11730d93b/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.client.vue")['default']>
    'LazyTresCanvas': LazyComponent<typeof import("../../node_modules/.pnpm/@tresjs+nuxt@4.0.0_magicast@0.3.5_rollup@4.52.0_three@0.180.0_vite@7.1.6_jiti@2.5.1_lig_fb7d552ca8598111e4dec8a11730d93b/node_modules/@tresjs/nuxt/dist/runtime/TresCanvas.server.vue")['default']>
    'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/pages/runtime/page")['default']>
    'LazyNoScript': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['NoScript']>
    'LazyLink': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Link']>
    'LazyBase': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Base']>
    'LazyTitle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Title']>
    'LazyMeta': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Meta']>
    'LazyStyle': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Style']>
    'LazyHead': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Head']>
    'LazyBody': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/head/runtime/components")['Body']>
    'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/nuxt-island")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/.pnpm/nuxt@4.1.2_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_eslint@9.36.0_jiti@_91193e1fb0eef0f3be3ee18ff5775fc2/node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
