name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics SVG
        uses: lowlighter/metrics@latest
        with:

          token: ${{ secrets.METRICS_TOKEN }}


          filename: metrics/github-metrics.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update github-metrics.svg"
          committer_token: ${{ secrets.METRICS_TOKEN }}
          user: Noel-Schmidt
          template: classic
          base: header, repositories, metadata
          config_timezone: Europe/Berlin
          config_animations: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: percentage
          plugin_languages_threshold: 2%
          plugin_lines: yes
          plugin_traffic: yes
